image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore

tasks:
  - init: pip3 install -r requirements.txt
    command: python3 python3 test_main.py
